### ISSUE TITLE
teuxdeux.com [Account]

### ISSUE THREAD

**Issue by Anshuman-Verma** [aviaryan/awesome-no-login-web-apps#100]
Minimalist but attractive, Teuxdeux is a web-based task management app known for its horizontal and calendar-like interface. This lets you add tasks, strike them off, and jump from one day to another – all within one clean view.
Only problem is that it  provides a 30 day trial after which it's 12$ a year. :disappointed: 
Lemme know if  we need this @aviaryan.

**Comment by aviaryan** [comment]
No, there are better free apps available.
