### ISSUE TITLE
waveaccounting.com/about-us/ [Account]

### ISSUE THREAD

**Issue by Anshuman-Verma** [aviaryan/awesome-no-login-web-apps#101]
If numbers are not your specialty, life just got a bit easier. Wave is a free accounting application that looks after your bookkeeping so you can focus on your work. For example, it can automatically categorize your expenses, and it learns as you use the program. You can also access Wave through its Google Chrome app.
Let me know if we need this @aviaryan

**Comment by aviaryan** [comment]
It looks too big / versatile to add it as an app. Plus it's `[account]`. I think we shouldn't include it.
