### ISSUE TITLE
choosemypc.net

### ISSUE THREAD

**Issue by Anshuman-Verma** [aviaryan/awesome-no-login-web-apps#103]
It’s a very simple app that asks you to set your budget, select which country you’re in (only four supported at the moment), and whether or not you plan to overclock your system. The app will give you a complete list of parts to buy and you can add other parts to the PC such as an optical drive. The list of parts updates but keeps you under or on budget.
Can this go in search engines @aviaryan ?

**Comment by aviaryan** [comment]
Ok.
