### ISSUE TITLE
gifdeck.in

### ISSUE THREAD

**Issue by Anshuman-Verma** [aviaryan/awesome-no-login-web-apps#104]
it’s an amazing little service that turns presentations on SlideShare into GIFs. By default, it will convert the first ten slides though you can include more if you need to. The final output GIF can be saved to your local drive and used just about any way you want.
Need this in Graphics, Image and Design @aviaryan ?

**Comment by aviaryan** [comment]
It's more like a slideshare to gif converters. Therefore it should go in File Converters.
