### ISSUE TITLE
postfity.com [Acc]

### ISSUE THREAD

**Issue by Anshuman-Verma** [aviaryan/awesome-no-login-web-apps#105]
Postify is one such service that lets you schedule posts to Twitter and Facebook for free. You can schedule up to ten posts and it supports multiple Twitter accounts in addition to letting you manage Facebook pages.
What you will appreciate about Postify right off the bat is its clean interface.
How about  adding this in utilities sections @aviaryan ?

**Comment by aviaryan** [comment]
Cool. Please do so.
