### ISSUE TITLE
10MinuteMail.com

### ISSUE THREAD

**Issue by aashutoshrathi** [aviaryan/awesome-no-login-web-apps#114]
By clicking on the link below, you will be given a temporary e-mail address. Any e-mails sent to that address will show up automatically on the web page. You can read them, click on links, and even reply to them. The e-mail address will expire after 10 minutes. 

Why would you use this? Maybe you want to sign up for a site which requires that you provide an e-mail address to send a validation e-mail to. And maybe you don't want to give up your real e-mail address and end up on a bunch of spam lists. This is nice and disposable. And it's free. Enjoy! 

[https://10minutemail.com/](https://10minutemail.com/)

**Comment by Anshuman-Verma** [comment]
What is this ? Why is this ? What should i do with this ? How do i know if it helps me or not ? Why this issue is on this repo ? Why do u exist ? Why does this site exist ? What is the comment button below green ? Is this an app or a form or a list ? Why the issue number is 114 ? -_- @aashutoshrathi

**Comment by akash1997** [comment]
This site is good. I think this should be included in the list.

**Comment by aashutoshrathi** [comment]
@Anshuman-Verma updated it, sorry for inconvenience

**Comment by Anshuman-Verma** [comment]
Looks good, @aashutoshrathi 
Which section looks good for this  ?

**Comment by akash1997** [comment]
I think this can be added to Privacy section, since the main motive is privacy.

**Comment by aashutoshrathi** [comment]
It can also be in communication as 
FaxZero - Send an online fax for free.
is placed in Communication

**Comment by Anshuman-Verma** [comment]
Privacy seems more appropriate to me, anyways let @aviaryan have his say.

**Comment by akash1997** [comment]
on second thought, I think @aashutoshrathi is right, it would be more relevant under communication. If tlk.io is under communication, this also belongs there I guess. Anyways, as @Anshuman-Verma mentioned, let @aviaryan have his say. 😄

**Comment by Monal5031** [comment]
> What is the comment button below green ? Is this an app or a form or a list ?

@Anshuman-Verma It should rather be `Why` than `What' :P

**Comment by aviaryan** [comment]
As @akash1997 pointed out earlier, privacy is the major motive behind this app and therefore it should go in privacy. 
You won't use this for regular communication as the email address will expire after 10 minutes. 
The main reason this app exists is because of the privacy factor, so privacy. 🎉
