### ISSUE TITLE
Brainfuck Visualizer

### ISSUE THREAD

**Issue by aashutoshrathi** [aviaryan/awesome-no-login-web-apps#117]
Brainfuck is a turing-complete minimal programming language. It designed to implement easily on any programming language.
Brainfuck language consist with a simple machine model, a pointer and 8 command (character).
This link is Javascript Brainfuck Interpreter + Visualizer. 
Helps to understand how your code is working.
[Brainfuck Visualizer](http://fatiherikli.github.io/brainfuck-visualizer/)
Should this be added in Programming Tools under your curated list ?

**Comment by aviaryan** [comment]
It runs the code also so it is more suited for Programming Editors/IDEs category.

**Comment by aashutoshrathi** [comment]
Should I send a PR ?
