### ISSUE TITLE
Privacy Error in Fuge.it 's link

### ISSUE THREAD

**Issue by aashutoshrathi** [aviaryan/awesome-no-login-web-apps#118]
Link of Fuge.it in curated list is [https://fuge.it/](https://fuge.it/) which is giving privacy error
**Your connection is not private**
as the security certificate expired 379 days ago.
Is there anything we can do to fix it ?
Somehow [http://fuge.it/seedbox](http://fuge.it/seedbox) is working 😕

**Comment by aviaryan** [comment]
For now, we can link to another page like http://fuge.it/howitworks

**Comment by aashutoshrathi** [comment]
So, should I send a PR ?

**Comment by aviaryan** [comment]
@aashutoshrathi Yes, please.
