### ISSUE TITLE
Inconsistent file extensions formatting

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/awesome-no-login-web-apps#121]
There are instances in the README where we have file types (XLS, PNG) written as (xls, png) etc.. 
We need to follow a consistent style where all abbreviations and file-types are written in full caps in order to qualify for awesome list.
Therefore this issue needs fixing.

**Comment by akash1997** [comment]
shall i do it?

**Comment by aviaryan** [comment]
@akash1997 Yes, sure. Thanks.

**Comment by akash1997** [comment]
Done! I've sent a PR with the necessary changes. I have double checked the document, even then if there are corrections, kindly inform me! 😃
