### ISSUE TITLE
Sorting List for Ease of Access 

### ISSUE THREAD

**Issue by aashutoshrathi** [aviaryan/awesome-no-login-web-apps#125]
Should we sort whole list alphabetically, so that its easy for user to find the section they are searching for ?

**Comment by aviaryan** [comment]
We can sort the list section-wise. This might not be a pressing issue right now because we have very few sections. But nevertheless, it is a good practise to intake. 
If you want, you can send a PR sorting the sections.

**Comment by aashutoshrathi** [comment]
@aviaryan 
So, Should I sort all the section's title alphabetically or Each section's content alphabetically ?

**Comment by aviaryan** [comment]
Section's title alphabetically. 
I am not sure about sorting the individual contents alphabetically because the order there can be used to tell readers about the relative quality of the apps, which app was added first and so on.

**Comment by aashutoshrathi** [comment]
Okay that seems to be a good idea 

> sorting the individual contents alphabetically because the order there can be used to tell readers about the relative quality of the apps, which app was added first and so on.

I will send PR as soon as pending PRs get merged, so that no file conflict occurs
