### ISSUE TITLE
KrutiDev to Unicode (and vice versa) Converter

### ISSUE THREAD

**Issue by aashutoshrathi** [aviaryan/awesome-no-login-web-apps#128]
**[KrutiDev to Unicode](http://wrd.bih.nic.in/font_KtoU.htm)**

This simple tool helps to convert old and orthodox KrutiDev Fonts to Unicode (Mangal) font for easy sharing and also because Mangal font is Unicode based, So supported all over the web.
For eg : converting 

> ";qfudksM" 

to 

> "युनिकोड"

Can I add this to **[Text Based Tools](https://github.com/aviaryan/awesome-no-login-web-apps#text-tools)** Sections ?

**Comment by aviaryan** [comment]
The use-case for this is too narrow. I am not sure if we should have this or not. 
And Text Based Tools is not a good section for this either, since the tools in that category have mostly to do with text analysis. This is more like conversion. Utilities section would be better I guess.
