### ISSUE TITLE
CSS Typeset

### ISSUE THREAD

**Issue by Anshuman-Verma** [aviaryan/awesome-no-login-web-apps#138]
CSS Type Set lets you create typography designs and generates the CSS for you. Just paste in text you want to modify, and then use the options at the bottom to customize it and it will generate the CSS in real-time.
[CSS Typeset](http://csstypeset.com/)
Is programming tools section appropriate for this @aviaryan ?

**Comment by aviaryan** [comment]
Yes it should do.
