### ISSUE TITLE
CSS Menu Generator

### ISSUE THREAD

**Issue by Anshuman-Verma** [aviaryan/awesome-no-login-web-apps#140]
This generator is great for when you just need a quick, simple drop-down menu. Just choose a style, create your menu items, and download the respective CSS for your desired menu.
[CSS Menu Gen.](http://www.cssmenumaker.com/)
Is *Programming Tools* section appropriate for this  @aviaryan ?

**Comment by aviaryan** [comment]
Yes, that should work for now.
