### ISSUE TITLE
IcoMoon

### ISSUE THREAD

**Issue by aashutoshrathi** [aviaryan/awesome-no-login-web-apps#148]
IcoMoon is an icon solution, providing three main services: Vector Icon Packs, The IcoMoon App, and hosting icons as SVGs or fonts.
Can this go into *Graphics, Image and Design* Section.

**Comment by aviaryan** [comment]
We can have https://icomoon.io/app as the link.
I see that the main feature it has is the app I linked above. It allows you to select some free icons and then export them to svg, png or font.

**Comment by Monal5031** [comment]
Isn't this closed in #152 😆
