### ISSUE TITLE
CSSmatic

### ISSUE THREAD

**Issue by anshumanv** [aviaryan/awesome-no-login-web-apps#159]
[CSSmatic](http://www.cssmatic.com/)

> The ultimate CSS tools for web designers

A web-app to visualize CSS changes in browser itself using user friendly UI and lets the user download appropriate CSS or compiled SASS as per the preferences.

Currently supports 4 tools : 
* Gradient Generator
* Border Radius
* Noise Texture
* Box Shadow

The bunch of tools provided are amazing and time-saving.

This app should be appropriate for *Programming Tools* section.

**Comment by aviaryan** [comment]
Looks good. Please send a PR. 😄
