### ISSUE TITLE
WikiWhere

### ISSUE THREAD

**Issue by aashutoshrathi** [aviaryan/awesome-no-login-web-apps#162]
[WikiWhere](https://wiki-where.github.io/) , Online Trivia game to check your knowledge on major cities and their geographical location.
This can go in _Games_

**Comment by aviaryan** [comment]
I see the following error when I open the website. Any ideas?

![](https://i.imgur.com/4jjZJJE.png)

**Comment by aashutoshrathi** [comment]
Oh !!, I think it is _Google Chrome_ specific

**Comment by aviaryan** [comment]
I just tried it now and it still doesn't work. Since Chrome owns the highest percentage of browser usage, I don't think we should add it.
