### ISSUE TITLE
geography-map-games

### ISSUE THREAD

**Issue by anshumanv** [aviaryan/awesome-no-login-web-apps#163]
[geography-map-games](http://www.geography-map-games.com/) `[Account]` 

This is an interactive app to test your geography, flags, capitals knowledge and compete with players worldwide, You can get various stats, ranks etc.

Form clubs with your teammates and play.
Thinking to add this in games section.

*extra* - I've been using this app with handle [natsu7](http://www.geography-map-games.com/_pageid181_upid=69407.html) and currently hold 28WR in Prefectures of Japan 😛

**Comment by aviaryan** [comment]
Sounds good. Please send a PR.

**Comment by aviaryan** [comment]
Let's try to avoid `[Account]` types as much as possible.
