### ISSUE TITLE
ongaku - Anime Radio

### ISSUE THREAD

**Issue by aashutoshrathi** [aviaryan/awesome-no-login-web-apps#165]
[ongaku](https://ongaku.js.org/), Online Anime Radio.

**Comment by aviaryan** [comment]
Good addition. BTW, the online app is not Electron based, right?

**Comment by aashutoshrathi** [comment]
Oh!!, Sorry, It also have a Desktop app (Electron based).

**Comment by Anshuman-Verma** [comment]
This one is a web-app, the electron based desktop port is [here](https://github.com/Anshuman-Verma/ongaku-desktop).

Btw thanks @aashutoshrathi for this addition. 😄

**Comment by aashutoshrathi** [comment]
Should I add it in _Music, Radio and Podcasts_ ?

**Comment by aviaryan** [comment]
@aashutoshrathi Yes

**Comment by Anshuman-Verma** [comment]
Please close this @aashutoshrathi 😄
