### ISSUE TITLE
Openings.moe Anime Video Player

### ISSUE THREAD

**Issue by Lucifer24** [aviaryan/awesome-no-login-web-apps#170]
[Opening.moe](http://openings.moe/?video=Opening2-K-On!!) Oniline Anime Video Player

**Comment by aviaryan** [comment]
Looks awesome. Please send a PR. 

PS - The animation in [Ending1-5CentimetersPerSecond](http://openings.moe/?video=Ending1-5CentimetersPerSecond) is out of this world.

**Comment by Anshuman-Verma** [comment]
Have to agree with @aviaryan
