### ISSUE TITLE
Flaming Text

### ISSUE THREAD

**Issue by Monal5031** [aviaryan/awesome-no-login-web-apps#173]
[Flaming text](http://flamingtext.com/) online design logo creator.

**Comment by aviaryan** [comment]
@Monal5031 Nice tool. Please send a PR.
PS - We can use it to do #31 also.

**Comment by Monal5031** [comment]
@aviaryan Sure we can do that but it won't look that much good and also would become unrelated I guess.
If you want I can try some ideas over #31

**Comment by aviaryan** [comment]
> If you want I can try some ideas over #31

Yea, please go ahead. :smile:
