### ISSUE TITLE
DiffNow

### ISSUE THREAD

**Issue by aashutoshrathi** [aviaryan/awesome-no-login-web-apps#177]
https://www.diffnow.com/
Advanced, online and free File Difference checking, with options like Upload file, compare files by their links or Text Input.
It is better than existing entry in *Text Based Tools* as the prev. one. doesn't give you options for uploading files and when it comes to comparing large files (test cases), we better upload one file.

**Comment by aviaryan** [comment]
@aashutoshrathi Sure. We should have it but let's keep the existing one too. (we can have max 2 applications/type)
