### ISSUE TITLE
Formoid

### ISSUE THREAD

**Issue by Monal5031** [aviaryan/awesome-no-login-web-apps#178]
[http://formoid.com/feedback/registration-form-template-html-choice-of-font-and-size-P.html](http://formoid.com/feedback/registration-form-template-html-choice-of-font-and-size-P.html)

Formoid is a free desktop app that helps you easily create signup forms, surveys, order forms, event registrations and more in a few seconds without writing a single line of code.

Its a desktop app, not sure if we can add this here.

**Comment by aviaryan** [comment]
No, I don't think we can add a desktop app here.
