### ISSUE TITLE
Add .coafile

### ISSUE THREAD

**Issue by aashutoshrathi** [aviaryan/awesome-no-login-web-apps#183]
Add bears for YAML, MD and sh files to manage code quality for this repository.

- [x] Assign me to this issue.

**Comment by Monal5031** [comment]
Please don't add the mysterious MDBear 🙏 we can add bear to check links also.

**Comment by aashutoshrathi** [comment]
For checking links, we have a beautifully written script

**Comment by Monal5031** [comment]
Which gives a very ugly output.

**Comment by aviaryan** [comment]
@aashutoshrathi @Monal5031  What will those bears do? Please list them in points.

**Comment by Monal5031** [comment]
- YAMLLintBear
- InvalidLinkBear
views? @aashutoshrathi

**Comment by aviaryan** [comment]
@aashutoshrathi Can you please provide an update on the bears that you propose to add.

**Comment by aashutoshrathi** [comment]
Actually, @Monal5031 know about coala bears better than me. 😅 
Sorry, for the late response.
