### ISSUE TITLE
error in ascii link

### ISSUE THREAD

**Issue by Monal5031** [aviaryan/awesome-no-login-web-apps#186]
https://ascii.li is giving an error, build failing due to it.
ping @aviaryan

**Comment by aviaryan** [comment]
@Monal5031 Thanks for reporting. Please send a PR to fix the same.

**Comment by Monal5031** [comment]
Somehow I checked again it is working now :confused:

**Comment by aviaryan** [comment]
It shows a domain for sale message now. I think we can remove it. Will you like to send a PR? @Monal5031
