### ISSUE TITLE
youtubemp3.to (Internet Downloaders category) no longer works

### ISSUE THREAD

**Issue by lmintmate** [aviaryan/awesome-no-login-web-apps#203]
The homepage of youtubemp3.to says the following:
> Effective 6/24/2018 YouTubemp3.to will no longer function. We are discontinuing service of the website. More information will be release here and on our Facebook page in the coming days. Please follow our Facebook page for updates.

In addition when one attempts to use the service anyway, the following message is displayed:
> The video cannot be converted because our website has closed.

Since this service no longer works, the entry should probably be removed. Besides onlineconverter (the entry below this one) covers the downloading of mp3 files from youtube videos just fine.
Thanks in advance for understanding.

**Comment by aviaryan** [comment]
You are right. Do you want to send a PR for this?

**Comment by lmintmate** [comment]
Just sent my PR. Please let me know if there's anything else I should do.

**Comment by aviaryan** [comment]
Thank you @lmintmate.
