### ISSUE TITLE
Discord is not loginless

### ISSUE THREAD

**Issue by squatica** [aviaryan/awesome-no-login-web-apps#277]
Accessing Discord leads to this page
![discord](https://user-images.githubusercontent.com/53292272/145526207-1d24c31a-0d50-48a7-9845-58f342d57c0a.png)

**Comment by aviaryan** [comment]
Don't go through that option. Click on "Open Discord in your browser" on the homepage. Add username. Then add a Date of birth but don't add anything in the email prompt. That way, you can create an account without email. I just did it right now.

<img width="1755" alt="Screenshot 2021-12-10 at 1 41 09 PM" src="https://user-images.githubusercontent.com/4047597/145539850-9d0d6238-09af-4c06-a7eb-e48bdd015b4f.png">
