### ISSUE TITLE
Create a logo/illustration for the list and add it to README

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/awesome-no-login-web-apps#31]
It would be nice to have a logo for the list like https://github.com/sindresorhus/awesome-electron

PRs are most welcome.

**Comment by aviaryan** [comment]
@ansarimofid Want to help?

**Comment by ansarimofid** [comment]
I will work on this. But it may take some time.

**Comment by aviaryan** [comment]
@ansarimofid Bro, please. 🙏🏻

**Comment by aviaryan** [comment]
@ansarimofid It would be great if you can work on this.

**Comment by Monal5031** [comment]
![coollogo_com-12564504](https://user-images.githubusercontent.com/21009189/30785864-dca014ae-a18a-11e7-8934-d88e21c70c51.png)

@aviaryan Some random experiments with flamingtext 😅

**Comment by anshumanv** [comment]
Please mark this as `hacktoberfest` to attract contributors.

**Comment by aviaryan** [comment]
@anshumanv done.
@Monal5031 haha, there's some irony there.
