### ISSUE TITLE
Additional links [ezgif, rollapp, skype and more]

### ISSUE THREAD

**Issue by xmesaj2** [aviaryan/awesome-no-login-web-apps#33]
http://rollapp.com
requires account, let's you run most of Windows/Linux apps within a browser.

http://realtimeboard.com
requires account, best collaborative drawing I've used, supports screen sharing, video&voice communicatios

http://web.skype.com
web-based version of Skype communicator

http://ezgif.com
no account required, manipulating gif files with lots of possiblities

https://aurifexlabs.com/
http://mightyfingers.com/
online html5 game phaser.js IDEs

https://color.adobe.com/
Color scheme designer

http://isup.me/
"is website down for everyone or just me?"

http://wordsafety.com/
check if words are abusive in any languages

https://codenvy.com/
requires account, online web-based IDE

**Comment by arpit1997** [comment]
Codenvy is already in the list.

**Comment by aviaryan** [comment]
@xmesaj2 Can you please send a pull request for this. Also please pay close attention to [CONTRIBUTING.md](https://github.com/aviaryan/awesome-no-login-web-apps/blob/master/CONTRIBUTING.md) before submitting your patch.

**Comment by xmesaj2** [comment]
@aviaryan should I make 1 commit per site then submit PR or all in just single commit?

**Comment by xmesaj2** [comment]
submitted PR skipping Abra and MightyEditor because they are rather focused on one html5 game library

**Comment by aviaryan** [comment]
@xmesaj2 Please don't add Skype as it requires account and we already have similar options that don't require login. Rest all seems good. 
Ideally we would like one app per PR but in this case we can make an exception. 
Please make the title of your PR as `Added X,Y,Z,.... and B`. 1 commit per site should be better.

**Comment by aviaryan** [comment]
Closed by #34
