### ISSUE TITLE
Add ImageTitan

### ISSUE THREAD

**Issue by Monal5031** [aviaryan/awesome-no-login-web-apps#37]
[ImageTitan](http://www.imagetitan.com/) File hosting website requires no login for hosting images but has some limitations over file size,

**Comment by aviaryan** [comment]
We already have an image hosting website listed there. So at most, only one more similar website is permitted. Please decide between #36 and this. Or you can even suggest a better alternative.

**Comment by Monal5031** [comment]
@aviaryan #36 is better than this one as it provide's more file types and more size.

**Comment by aviaryan** [comment]
@Monal5031 Then please send a PR for it.

**Comment by Monal5031** [comment]
@aviaryan This issue should be closed as #36 was added over this.
