### ISSUE TITLE
Add goo.gl

### ISSUE THREAD

**Issue by aashutoshrathi** [aviaryan/awesome-no-login-web-apps#40]
A URL shortening service by Google 
[goo.gl](https://goo.gl/)

**Comment by aviaryan** [comment]
@aashutoshrathi Thanks for the thought but we already have 2 url shorteners in that list. 
If you think this url shortener has a competitive edge for others, then only we can add it. 
Thoughts ?

**Comment by aashutoshrathi** [comment]
@aviaryan no such competition, but I think this one is by Google, so can be trusted more..

**Comment by aviaryan** [comment]
bitly and is.gd are old trusted companies so they won't just shut down their services and run away. So an argument like more trustable is not valid here.

**Comment by Anshuman-Verma** [comment]
goo.gl lets you keep track of the traffic generated through the link and also provides the QR code of the shortened link. That's quite and advantage.

**Comment by Anshuman-Verma** [comment]
Okay !
