### ISSUE TITLE
Add Multcloud

### ISSUE THREAD

**Issue by mohitkyadav** [aviaryan/awesome-no-login-web-apps#41]
Multcloud is a free service, helps to manage multiple cloud accounts, you can manage, move, copy and migrate files between cloud services. Supports all cloud services, all.
Initially 2 TB of cloud storage for free on Multicloud. Supports downloading large files up to 2TB(remaining space on the cloud), can directly download files to your drive or Multcloud. 

It's awesome.

https://www.multcloud.com/home

**Comment by aviaryan** [comment]
Looks nice. Please send a PR.
Btw, should it be tagged `Account`? I see there is an option to use it without giving your email. And it seems to have most of the features.
