### ISSUE TITLE
typingweb.com query

### ISSUE THREAD

**Issue by Anshuman-Verma** [aviaryan/awesome-no-login-web-apps#80]
Should we include typingweb.com into the list ?
This web-app takes us through a course to master touch typing, encourages users to practice by providing them with badges and other stuff. We are short of such web-apps too.
Need Account to track progress and accumulate badges.
Let me know if we need this in the list @aviaryan .

**Comment by aviaryan** [comment]
Yes, it's perfectly suited for our list.

**Comment by Anshuman-Verma** [comment]
Which section is most suited for this web-app ? Utilities or Misc. ? 
Do let me know beforehand so I can send in a clean mergable PR which is convenient to review at one go.
Thanx for looking into the issue @aviaryan, looking forward to sending more PRs.

**Comment by aviaryan** [comment]
Utilities
