### ISSUE TITLE
acronymcreator.net

### ISSUE THREAD

**Issue by Monal5031** [aviaryan/awesome-no-login-web-apps#82]
A webapp that gives acronym for any project, organization, algorithm or anything, only condition is that there should be at least two words in the name.
link : [http://acronymcreator.net/](http://acronymcreator.net/)

**Comment by Anshuman-Verma** [comment]
We are short of such web-apps. Nice addition @Monal5031 . :tada:  
This can probably go in text-based tools section, what say @aviaryan .

**Comment by aviaryan** [comment]
text based tools are generally related to text (paragraph) processing. 
This is more suited for utilities.

**Comment by Monal5031** [comment]
@Anshuman-Verma I also found a Project name generator but it wasn't that useful.
@aviaryan So shall I add it in utilities?

**Comment by Anshuman-Verma** [comment]
@Monal5031 nice, if anyhow you're doubtful to add stuff, open an issue.
Yes, add it in utilities section (that's what @aviaryan would say). :+1:
