### ISSUE TITLE
ifttt.com [Account]

### ISSUE THREAD

**Issue by Anshuman-Verma** [aviaryan/awesome-no-login-web-apps#84]
This web-app lets us create a connection between all our online accounts and manage them by signing up. This makes account management real convenient since we can manage all our accounts on one platform and saves us time to manage all accounts individually. 
This can be a valuable addition to the list.
Views @aviaryan ?

**Comment by aviaryan** [comment]
Sure, please go ahead.

**Comment by Anshuman-Verma** [comment]
Which section seems most appropriate ? To me Utilities or Miscellaneous, lemme know what u think is right so that i can send a PR. @aviaryan

**Comment by aviaryan** [comment]
Misc should be good.
