### ISSUE TITLE
Otixo.com [Account]

### ISSUE THREAD

**Issue by Anshuman-Verma** [aviaryan/awesome-no-login-web-apps#85]
This web-app is a cross platform app for collaborating files hosted on online file hosting sites like Dropbox, Gdrive etc all in one place by creating one simple account, this can be a valuable addition to the list as there is no such web-app present till now in the list.
Let me know your views @aviaryan .

**Comment by aviaryan** [comment]
We have MultCloud

**Comment by Anshuman-Verma** [comment]
Wakatta.
