### ISSUE TITLE
http://www.todaytvseries.com/

### ISSUE THREAD

**Issue by Monal5031** [aviaryan/awesome-no-login-web-apps#91]
[http://www.todaytvseries.com/](http://www.todaytvseries.com/) offers downloads for tv series.

**Comment by Anshuman-Verma** [comment]
I dont think it fits the definition of an 'app' and is more like a list of download links clustered in one place.
I'm not suggesting to include this in the list @Monal5031.
Anyways let @aviaryan have his say . :tada:

**Comment by aviaryan** [comment]
Yes, like @Anshuman-Verma said, this is not suitable for the list. plus piracy issues.
