### ISSUE TITLE
woorank.com

### ISSUE THREAD

**Issue by Anshuman-Verma** [aviaryan/awesome-no-login-web-apps#93]
Use this web-app to research a website from the SEO perspective.
This even provides us with the website rank (Global & Local) based on the  traffic generated too.
Do let me know your views to include this into the list @aviaryan .

**Comment by aviaryan** [comment]
We can have it in Programming Tools but I think we already have some web SEO tools. Please do the appropriate.

**Comment by Anshuman-Verma** [comment]
This has an upper hand over others by providing a local and global rank on the basis of traffic generated, so let's make it the last web SEO tool we include in the programming section alright  ?
