### ISSUE TITLE
talltweets.com

### ISSUE THREAD

**Issue by Anshuman-Verma** [aviaryan/awesome-no-login-web-apps#94]
Tall Tweets helps you write tweets longer than 140 characters. You can publish mini-essays, paste Word documents, press releases and other long snippets of text on Twitter without any limits. You can even highlight text in picture tweets.
Let me know if we need this @aviaryan. (yes) ? suggest section : close issue.

**Comment by aviaryan** [comment]
Utilities.

**Comment by Anshuman-Verma** [comment]
Wakatta.
