### ISSUE TITLE
studio.stupeflix.com/en/

### ISSUE THREAD

**Issue by Anshuman-Verma** [aviaryan/awesome-no-login-web-apps#95]
Make amazing videos in seconds !
Just add photos, videos, music, and text. 
It's very easy, and super fun!
Let me know if we need this in the list @aviaryan .

**Comment by aviaryan** [comment]
Well if it doesn't require accounts, it's an obvious addition to the list. Even if it requires accounts, I don't think we have much video editors.

**Comment by Anshuman-Verma** [comment]
Right, I have a couple of  other video editors too, maybe we should strengthen the Pictures & Video section a bit. :yum:

**Comment by aviaryan** [comment]
Please add a Fixes ... comment in the PR so that issue closes automatically.
