### ISSUE TITLE
www.namegenerator.biz

### ISSUE THREAD

**Issue by Monal5031** [aviaryan/awesome-no-login-web-apps#98]
Its a name generator for many things including Team name, first name, last name, etc
[http://www.namegenerator.biz/](http://www.namegenerator.biz/)

**Comment by Anshuman-Verma** [comment]
I made a test team name generation and what it gave was:
- The plant salamanders
- The dangerous cockroaches
:laughing:

**Comment by Monal5031** [comment]
So where shall I add it?

**Comment by Anshuman-Verma** [comment]
I'm real bad at selecting sections so i won't say a thing, let @aviaryan  sir have his say about selecting section and whether we should have it in the list, names generated didn't look much promising to me to be honest. :laughing:

**Comment by aviaryan** [comment]
This webapp looks ordinary. I am sure there are better tools available for this.
